{"name": "test_broken", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'broken.json'", "trace": "self = <test_allure_feature.TestLogin object at 0x0000025F048864C0>\n\n    @allure.severity(allure.severity_level.TRIVIAL)\n    @allure.story(\"测试broken用例\")\n    @allure.issue(\"https://www.cnblogs.com/linuxchao/\", \"错误链接\")\n    def test_broken(self):\n        \"\"\"broken\"\"\"\n>       with open(\"broken.json\", \"r\", encoding='utf8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'broken.json'\n\ntest_allure_feature.py:175: FileNotFoundError"}, "description": "broken", "start": 1611720923239, "stop": 1611720923239, "uuid": "5d065181-9ee6-4995-b8b6-b7e369e2a1b0", "historyId": "9ddd5d361e93b192deee1aec36bd08a6", "testCaseId": "e9bc689121f6709cb74ce2273f171b8e", "fullName": "pytest_allure.test_allure_feature.TestLogin#test_broken", "labels": [{"name": "severity", "value": "trivial"}, {"name": "story", "value": "测试broken用例"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "pytest_allure"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200914AAyx"}, {"name": "thread", "value": "1668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_allure.test_allure_feature"}], "links": [{"type": "issue", "url": "https://www.cnblogs.com/linuxchao/", "name": "错误链接"}]}