{"name": "test_login_fail[测试用户名错误, 密码错误用户名:linux密码linux期望值{'code': 1004, 'msg': '用户名或密码错误', 'data': None}]", "status": "passed", "description": "测试用户名或密码错误", "steps": [{"name": "输入用户名", "status": "passed", "parameters": [{"name": "user", "value": "'linux'"}], "start": 1611720923166, "stop": 1611720923166}, {"name": "输入密码", "status": "passed", "parameters": [{"name": "pwd", "value": "'linux'"}], "start": 1611720923166, "stop": 1611720923166}], "parameters": [{"name": "data", "value": "{'case': '用户名错误, 密码错误', 'user': 'linux', 'pwd': 'linux', 'expected': {'code': 1004, 'msg': '用户名或密码错误', 'data': None}}"}], "start": 1611720923165, "stop": 1611720923166, "uuid": "ab154da9-3b9c-4cbb-9b8e-e60a2aa83b9a", "historyId": "4d41a415d5aa5ba84429e3225f65c70e", "testCaseId": "aa77bd5a391f291f3c0ff3906d95c794", "fullName": "pytest_allure.test_allure_feature.TestLogin#test_login_fail", "labels": [{"name": "story", "value": "测试登录失败"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "pytest_allure"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200914AAyx"}, {"name": "thread", "value": "1668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_allure.test_allure_feature"}]}